[package]
name = "lib-crates"
version = "0.1.0"
edition = "2021"
authors = ["Gustavo Augusto <gustavoaugustocar@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
